# Generated by Django 5.1.3 on 2024-11-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currentsalon_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.DeleteModel(
            name='CurrentSalon',
        ),
    ]
