# Generated by Django 5.1.3 on 2024-11-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='start_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Стоимость услуги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
