# Generated by Django 5.1.3 on 2024-12-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_master_start_cost_alter_slider_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='name',
            new_name='salon_name',
        ),
    ]
