# Generated by Django 5.1.3 on 2024-12-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_name_salon_salon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='salon_name',
            new_name='name',
        ),
    ]
