# Generated by Django 5.1.3 on 2024-12-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tags_master_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название тега'),
        ),
    ]
