# Generated by Django 5.1.3 on 2024-12-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tags_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='masters', to='api.tags', verbose_name='Теги'),
        ),
    ]
